version: 2
updates:
  # --- root ---
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    versioning-strategy: increase
    groups:
      bun:
        patterns:
          - "*"
    commit-message:
      prefix: "fix"
      include: "scope"

  # --- GitHub Actions ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "fix"
      include: "scope"
