name: Renovate auto approve

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled

permissions: {}

jobs:
  approve:
    uses: $/.github/workflows/renovate-auto-approve.yml
    permissions:
      pull-requests: write
